my_tamr_instance:
    host: $TAMR_TOOLBOX_HOST    # Example: "10.0.0.0", or "0.0.0.0", or "localhost"
    protocol: "http"
    port: "9100"
    username: 'admin' 
    password: $TAMR_TOOLBOX_PASSWORD  # Example: "abc123"

logging_dir: "/full/path/to/logging/directory"

address_validation:
    googlemaps_api_key: $GOOGLEMAPS_API_KEY
    address_mapping_folder: "path/to/local/address/mapping/"
    address_columns:    # Ordered list of address column names -- only needed if validating locally
      - addressLine1
      - city
      - state
      - postalCode

datasets:
    my_dataset_to_be_addr_validated:
        name: "address_validation_demo.csv"
        address_columns:    # Ordered list of address column names in this dataset
          - addressLine1
          - city
          - state
          - postalCode
    my_addr_validation_mapping:
        name: "address_validation_mapping"