name: Publish to PyPi

on:
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Upgrade wheel
        run: pip install --upgrade wheel==0.34.2 setuptools
      - name: Build wheel file
        run: python setup.py bdist_wheel sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          username: __token__

