name: Publish to PyPI

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Upgrade wheel
        run: pip install --upgrade wheel==0.34.2 setuptools
      - name: Build wheel file
        run: python setup.py bdist_wheel sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          user: __token__

