name: Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'The name of the branch or tag to publish to TestPyPI'
        required: true
      version_name:
        description: 'Value to use for version name when publishing.  Cannot be the same as any previously used version name.  Consider the current version followed by the date and another number, e.g. 1.1.1.3.4.21.1'
        required: true

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}
      - name: Set version
        run: echo ${{ github.event.inputs.version_name }} > version.txt
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upgrade wheel
        run: pip install --upgrade wheel==0.34.2 setuptools
      - name: Build wheel file
        run: python setup.py bdist_wheel sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          user: __token__

